apiVersion: certificates.k8s.io/v1
kind: CertificateSigninRequest
metadata:
  name: svillars
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JUQ0NBVlVDQVFBd0tERVJNQThHQTFVRUF3d0ljM1pwYkd4aGNuTXhFekFSQmdOVkJBb01DbXQxWW1WeQpibVYwWlhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNyNEVkSUV6Nk0yak0yCkJybllEYXVaQmFBR2htdE52VGY3SDU3ZTRzMWJOM2hUd0I5UGNKSGpRa251bzBQTEhoNFpsa0llSzFUMDBKNGgKRTRQdkhkeVZnZWJEVmw5UXVtSW81RVNkVjlJNUpQREJ3ejlvTTdodkVxYlphVXUvV3d5ZXpEblJ0clRwSFlUcAowMnNOMVk0SHJSOE5OUHhUM3ZEeUNqL1dVakVZSUJid1N0MndwVXVzek9PbjNxeVhxMFEwcEo5UUVpb29KcWtsClhxTzFiNER5ZGhOaThMdk9ycnhVT2U5by82M0dETkxUSUVLVnEzZGo5cEtKRG1YVEJ1UncxSUlsY1puNktwVjQKeGpVQVp1c2tBUVU1MFRybE9HZzdnNVJxV05TeXM2dXY4Yld3VVFCWjU1NUZGRmRzQTRqVGNjbUJaLzZvWEt5OApaNk5WYmpqUkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU9ydDE1b2dOSStBTFlGY2RtVDRzCmZuaVZBWUMvaWw2RVEwYkkrSE9XWUxqQTgzR2dZNyt0Rmt6UHYxWW1jdkI4cnpFR1I3UE5qWVhCaHFrcUtTY2cKRWNvVzlTL2twdlg3dG5MV0h1d2Uvb0ZSK0tIY2pRUXlTT1VRWjJGWk82NnUvcGE0YVJBak1vTXFKYWMyaWVuaApXM1UzS3NEUkhMdlkvT2ZtSTFrTXJJdmV3eHJBTTFvMzZhTDdsQmVVck85Vm0rekM0c1BUSmhDYTlkQ2cyVGlKCk5Hd0ZPRGhIZzJwV0hmOEMwVHBlZW1OUzk1VVpOYzhJNDJTNXp3cXpUR2o3TWhUM2tpOVFGSEUwNGxDanF2Q0IKZDN5OTNEV1RnUnlOaXRjSHA3eG9WMFpqcFRmaktSUTU0ME4vYkR1V3FwRTBJU3ZlbVBTNG5BZFZ6eWthZlFHMwpwUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=%
  signerName:kubernetes.io/kube=apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth