apiVersion: apps/v1
kind: Deployment
metadata:
  name: mideployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx   # El guion indica el inicio de UN contenedor
        image: nginx             # Sin guion, porque es parte del mismo contenedor
        ports:                   # 'ports' debe estar alineado con 'name' e 'image'
        - containerPort: 80      # Los puertos del contenedor